[
  {
    "py/tuple": [
      {
        "py/object": "objects.Link",
        "src": {
          "py/object": "objects.Exception",
          "type": "java.lang.IllegalArgumentException",
          "method": "org.apache.lucene.index.IndexingChain$PerField/invert:1209",
          "message": "Document contains at least one immense term in field=\"t%)_s\" (whose UTF8 encoding is longer than the max length 32766), all of which were skipped.  Please correct the analyzer to not produce such terms.  The prefix of the first immense term is: '[97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97, 97]...', original message: bytes can be at most 32766 in length; got 50000"
        },
        "dst": {
          "py/object": "objects.Exception",
          "type": "java.util.UnknownFormatConversionException",
          "method": "java.util.Formatter/checkText:2748",
          "message": "Conversion = ')'"
        }
      },
      {
        "py/id": 4
      }
    ]
  }
]
